name: ansible multi-deployment

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: docker build and push
        id: build-image
        env: |
          tag_value: ${{ github.sha }}
        run: |
          docker build -f Dockerfile -t 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:tag_value .
          docker push 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:tag_value
          
  # run-playbook:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: code checkout
  #       uses: actions/checkout@v5

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v5.0.0
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
  #         aws-region: us-west-1

  #     - name: Execute remote SSH commands using password
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ansibleadmin
  #         password: ${{ secrets.PASSWORD }}
  #         key: ${{ secrets.KEY }}
  #         script: |
  #           ansible-playbook docker-full.yaml --tags=deploy -vv
