name: ansible multi-deployment

on:
  push:
    branches:
      - main
env:
  tag_value: ${{ github.sha }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: docker build and push
        id: build-image
        run: |
          docker build -f Dockerfile -t 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }} .
          docker push 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }}
          
  # run-playbook:
  docker-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          aws-region: ap-south-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: AWS SSM Send-Command
      #   uses: peterkimzz/aws-ssm-send-command@master
      #   id: ssm
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
      #     aws-region: ap-south-1
      #     instance-ids: ${{ secrets.INSTANCE_ID }}
      #     working-directory: /home/ubuntu
      #     command: |
      #       docker pull 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }}
      #       docker rm -f Siva-docker
      #       docker run -itd -p 3000:3000 --name Siva-docker 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }}
      #     comment: docker deployed

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.INSTANCE_IP }}
          # username: ubuntu
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }}
            docker rm -f Siva-docker
            docker run -itd -p 3000:3000 --name Siva-docker 869588908060.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:${{ env.tag_value }}
