# This is a basic workflow to help you get started with Actionss

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  Image_url: 989007362438.dkr.ecr.us-east-1.amazonaws.com/default/image

jobs:

  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkoutcode
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY_ID }}
          aws-region: us-east-1
          
      - name: aws ecr login
        uses: aws-actions/amazon-ecr-login@v2

      - name: docker build and push to ecr
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.Image_url }}:${{ github.sha }}

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest  

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.0
  
      - name: SSM Send Command Action
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY_ID }}
          aws-region: us-east-1
          instance-ids: i-0ec4b8e2327941582
          command: |
          
            # Login to ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 989007362438.dkr.ecr.us-east-1.amazonaws.com
            
            # Pull the image
            docker   pull ${{ env.Image_url }}:${{ github.sha }}
            
            # Stop and remove old container if exists
            docker stop app || true
            docker rm app || true
            
            # Run new container
            docker run -d --name app -p 80:3000 ${{ env.Image_url }}:${{ github.sha }}
            
            
